platform :ios, '12.0'

inhibit_all_warnings!

target 'Chat' do
  use_frameworks!
	
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'SwiftLint'

	target 'ChatTests' do
	inherit! :search_paths
	pod 'Firebase/Auth'
	pod 'Firebase/Firestore'
	end

end
