desc "Build for testing"
lane :build_for_testing do |options|
  scan(
    workspace: './Chat/Chat.xcworkspace',
    clean: true,
    build_for_testing: true,
  )
  puts("Build for testing!")
end

desc "Run all tests"
lane :run_all_tests do |options|
  scan(
    workspace: './Chat/Chat.xcworkspace',
    test_without_building: true
  )
  puts("Run all tests!")
end

desc "Build and test"
lane :build_and_test do |options|
  build_for_testing
  run_all_tests
  puts("Build and test!")
end