name: UNIT/UI_tests
on: [push]
jobs: 
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      env:
        ImageOS: macos11
        PIXABAY_API_KEY: ${{ secrets.PIXABAY_API_KEY }}
        FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
      with:
        ruby-version: 2.6.8
        bundler-cache: true
    - name: Run
      run: bundle exec fastlane build_and_test
      