name: UNIT/UI_tests
on: [push]
jobs: 
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      env:
        ImageOS: macos11
      with:
        ruby-version: 2.6.9
        bundler-cache: true
    - name: Run
      run: bundle exec fastlane ios build_and_test