name: Notify
on: [push]

jobs:
  testing:
    name: Notify
    runs-on: self-hosted
    steps:
      - name: Send start notification to Discord
        uses: appleboy/discord-action@master
        with:
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
          color: "#8b9b9c"
          username: "GitHub Bot"
          message: |
            Tests started by 👤 ${{ github.actor }}
            From `${{ github.head_ref }}` to `${{ github.base_ref }}`
            Event `${{ github.event_name }}`